#
# stub function definition file for docstring parsing
#

def delmod(vis, otf=True, field='', scr=False):
    r"""
Deletes model representations in the MS

Parameters
   - vis_ (string) - Name of input visibility file (MS)
   - otf_ (bool=True) - Delete the on-the-fly model data keywords

      .. raw:: html

         <details><summary><i> otf = True </i></summary>

      - field_ (string='') - Select field using field id(s) or field name(s)

      .. raw:: html

         </details>
   - scr_ (bool=False) - Delete the MODEL_DATA scr col (if it exists)


Description
   **delmod** is a task to remove MODEL data from MeasurementSets.

   The MODEL can be either the scratch-less virtual model (stored in
   the MS SOURCE sub-table), and/or as model visibilities the
   MODEL_DATA column (e.g., written by the tasks **setjy**, **ft**,
   **tclean**). In cases where both representations are present, the
   virtual model is used over the scratch column model and there may
   be a need to remove the virtual model to allow the MODEL_DATA
   column to take effect.


.. _vis:

vis (string)
   | Name of input visibility file (MS)

.. _otf:

otf (bool=True)
   | Delete the on-the-fly model data keywords
   |                      Default=True
   | 
   |                      The 'otf' representation is the 'scratch-less'
   |                      model data, stored as keywords in the MS header
   |                      containing model data formation instructions.  It
   |                      is generated by the setjy, ft, and tclean tasks
   |                      (usescratch=False), and if present, overrides the
   |                      MODEL_DATA column (if present). If a user wishes
   |                      to use the MODEL_DATA column _after_ having
   |                      operated with the 'otf' representation, this task
   |                      can be used to delete the 'otf' represenatation
   |                      to make the MODEL_DATA column visible.  (Create
   |                      the MODEL_DATA column by using usescratch=True in
   |                      setjy, ft, or clean; or by running the clearcal
   |                      task with addmodel=True.)

.. _field:

field (string='')
   | Select field using field id(s) or field name(s)
   |                      Subparameter of otf
   |                      Default: '' (all fields' models will be deleted)

.. _scr:

scr (bool=False)
   | Delete the MODEL_DATA scr col (if it exists)
   |                      Default: False
   | 
   |                      Note: it is not possible to delete the MODEL_DATA
   |                      column per field.
   | 
   |                      If otf=F and scr=F, delmod will provide a listing
   |                      of the header field records.


    """
    pass
