#
# stub function definition file for docstring parsing
#

def delmod(vis, otf=True, field='', scr=False):
    r"""
Deletes model representations in the MS

Parameters
   - **vis** (string) - Name of input visibility file (MS) [1]_
   - **otf** (bool=True) - Delete the on-the-fly model data keywords [2]_

      .. raw:: html

         <details><summary><i> otf = True </i></summary>

      - **field** (string='') - Select field using field id(s) or field name(s) [3]_

      .. raw:: html

         </details>
   - **scr** (bool=False) - Delete the MODEL_DATA scr col (if it exists) [4]_


Description
   **delmod** is a task to remove MODEL data from MeasurementSets.

   The MODEL can be either the scratch-less virtual model (stored in
   the MS SOURCE sub-table), and/or as model visibilities the
   MODEL_DATA column (e.g., written by the tasks **setjy**, **ft**,
   **tclean**). In cases where both representations are present, the
   virtual model is used over the scratch column model and there may
   be a need to remove the virtual model to allow the MODEL_DATA
   column to take effect.

   

   .. rubric:: Parameter descriptions
      

   .. rubric:: *vis*
      

   The input MeasurementSet.

   .. rubric:: *otf*
      

   *otf=True* will remove the virtual model informatiom from the MS
   SOURCE sub-table.

   .. rubric:: *otf=True* expandable parameters
      

   .. rubric:: *field*
      

   The field ID or name to be selected.

   .. note:: **NOTE:** Currently the *field* selection only applies to the
      virtual model with *otf=True*, **not** the scratch MODEL_DATA
      column (*scr=True*)

   

   .. rubric:: scr
      

   *scr=True* will remove the scratch column MODEL_DATA.

   | 
   |




Details
   Explanation of each parameter

.. [1] 
   **vis** (string)
      | Name of input visibility file (MS)
.. [2] 
   **otf** (bool=True)
      | Delete the on-the-fly model data keywords
      |                      Default=True
      | 
      |                      The 'otf' representation is the 'scratch-less'
      |                      model data, stored as keywords in the MS header
      |                      containing model data formation instructions.  It
      |                      is generated by the setjy, ft, and tclean tasks
      |                      (usescratch=False), and if present, overrides the
      |                      MODEL_DATA column (if present). If a user wishes
      |                      to use the MODEL_DATA column _after_ having
      |                      operated with the 'otf' representation, this task
      |                      can be used to delete the 'otf' represenatation
      |                      to make the MODEL_DATA column visible.  (Create
      |                      the MODEL_DATA column by using usescratch=True in
      |                      setjy, ft, or clean; or by running the clearcal
      |                      task with addmodel=True.)
.. [3] 
   **field** (string='')
      | Select field using field id(s) or field name(s)
      |                      Subparameter of otf
      |                      Default: '' (all fields' models will be deleted)
.. [4] 
   **scr** (bool=False)
      | Delete the MODEL_DATA scr col (if it exists)
      |                      Default: False
      | 
      |                      Note: it is not possible to delete the MODEL_DATA
      |                      column per field.
      | 
      |                      If otf=F and scr=F, delmod will provide a listing
      |                      of the header field records.

    """
    pass
